config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # root to: "home#index"

  root to: "posts#index"

  resources :users, only: [:new, :index] do
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  get 'users/:username', to: 'users#show', as: 'user'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Image uploader
  include ImageUploader::Attachment(:image)

  # Validations

  validates :full_name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  # Associations
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def show
    @user = User.find_by(username: params[:username])

    return redirect_to root_path if @user.nil?

    @posts = Post.where(user_id: @user.id).order(created_at: :desc)
    @latest_posts = Post.all.order(created_at: :desc).limit(5)
  end

  def index
    @users = User.all
    redirect_to root_path
  end

  def new
    @user = User.new
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 vh-100" style="background-color: #9A616D;">
        <% if current_user == @user %>
            <div class="d-flex justify-content-end">
            <%= link_to '<i class="fas fa-sign-out-alt"></i>'.html_safe, destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-outline-danger btn-sm mt-3', title: 'Logout' %>
            </div>
        <% end %>
        <div class="row">
            <div class="col py-3">
                <% if @user.image_data %>
                    <%= image_tag @user.image_url, class: "img-fluid rounded-circle w-50 mx-auto d-block" %>
                <% else %>
                    <%= image_tag "https://as1.ftcdn.net/v2/jpg/03/53/11/00/1000_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg", class: "img-fluid rounded-circle w-50 mx-auto d-block" %>
                <% end %>
                <h4 class="text-center py-3 ">
                    <%= @user.full_name %><br />
                    <i><span class="text-white fs-6">@<%= @user.username %></span></i>
                </h4>
                <p class="text-center text-white fs-5 text-decoration-underline">
                    <%= @user.bio %>
                </p>

                <p class="text-center">
                    <i class="fa fa-envelope"></i> <%= @user.email %> 
                </p>
                <% if current_user == @user %>
                        <%= link_to "Edit profile", edit_user_registration_path, class: "btn btn-primary btn-sm mx-auto d-block mb-3 w-25" %>
                <% end %>
            </div>
        </div>
        <h5 class="text-white text-center"><%= @user.posts_counter %> Posts</h5>

        <% if current_user == @user %>
                <%= link_to "New post",  new_user_post_path(@user), class: "text-white btn btn-primary btn-sm mx-auto d-block mb-3 w-50" %>
        <% end %>
    </div>
    <div class="col-md-8 overflow-auto vh-100">
        <div class="card mt-3">
            <div class="card-header" style="background-color: #9A616D;">
                <h3 class="card-title"> My posts </h3>
            </div>
            <div class="card-body">
               <% if @posts.empty? %>
                   <p class="text-center my-3">No posts yet</p>
                   <%= link_to "New post",  new_user_post_path(@user), class: "btn btn-primary btn-sm mx-auto d-block mb-3" %>
                <% else %>
                    <% @posts.each do |post| %>
                        <div class="card mb-5">
                            <div class="card-header">
                                <h3 class="card-title <%= post.title.length > 50 ? "fs-5" : "fs-4" %> ">
                                    <%= link_to post.title, user_post_path(post.user, post), style: "color: #9A616D;" %>
                                </h3>
                            </div>
                            <div class="card-body">
                                <p class="card-text">
                                    <%= markdown(post.text.truncate(200)) %>
                                </p>
                                <div class="card-footer d-flex justify-space-between">
                                    <p class="card-text text-muted">
                                        <i class="fa fa-heart"></i> <%= post.likes_counter %> likes 
                                    </p>
                                    <p class="card-text text-muted">
                                        <i class="fa fa-comment"></i> <%= post.comments_counter %> comments
                                    </p>
                                </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            </div>
        </div>

        <h3 class="my-5">Recent posts</h3>
        <% @latest_posts.each do |post| %>
            <div class="card my-5">
                <div class="card-header">
                    <h3 class="card-title <%= post.title.length > 50 ? "fs-3" : "fs-4" %>">
                        <%= link_to post.title, user_post_path(post.user, post), style: "color: #9A616D;" %>
                    </h3>
                </div>
                <div class="card-body">
                    <p class="card-text">
                        <%= markdown(post.text.truncate(200)) %>
                    </p>
                    <p class="card-text text-muted">
                        Posted by <%= link_to post.user.username, user_path(post.user.username) %> on <%= post.created_at.strftime("%B %d, %Y") %>
                    </p>
                </div>
                <div class="card-footer d-flex justify-space-between">
                    <p class="card-text text-muted">
                        <i class="fa fa-heart"></i> <%= post.likes_counter %> likes 
                    </p>
                    <p class="card-text text-muted">
                        <i class="fa fa-comment"></i> <%= post.comments_counter %> comments
                    </p>
                </div>
            </div>
        <% end %>
    </div>
</div>