config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # root to: "home#index"

  root to: "posts#index"

  resources :users, only: [:new, :index] do
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  get 'users/:username', to: 'users#show', as: 'user'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 3, maximum: 250 }
  validates :text, presence: true, length: { minimum: 1 }
  validates :likes_counter, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :comments_counter, presence: true, numericality: { greater_than_or_equal_to: 0 }

  after_create :update_user_posts_counter

  private

  def update_user_posts_counter
    user.update(posts_counter: user.posts_counter + 1)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(3)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_post, only: %i[show destroy]
  before_action :set_user, only: %i[new create edit update]

  def index
    @posts = Post.all.order(created_at: :desc)
    @popular_posts = Post.all.order(likes_counter: :desc).limit(5)
    @latest_posts = Post.all.order(created_at: :desc).limit(10)
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @user.posts_counter += 1
    @user.save

    respond_to do |format|
      if @post.save
        flash[:notice] = 'Post was successfully created.'
        format.html { redirect_to user_post_path(@user, @post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @comment = Comment.new
    @like = Like.new
  end

  def new
    @post = Post.new
  end

  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to user_post_path(@user, @post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @username = @post.user.username
    if @post.destroy
      flash[:notice] = 'Post was successfully deleted.'
      redirect_to user_path(@username)
    else
      flash[:alert] = 'Something went wrong'
      redirect_to user_posts_path(@user)
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<section style="background-color: #9A616D;" , class="vh-100">
  <div class="container py-5">
    <div class="row w-75 mx-auto" style="background-color: #FFF;>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title text-center py-3">Edit your post</h3>
            </div>      
            <div class="panel-body">
                <%= bootstrap_form_with model: @post, url:user_post_path(@post.user, @post), method: :patch do |f| %>
                    <div class="form-group">
                        <%= f.text_field :title, placeholder: "Post title here", value: @post.title %>
                    </div>
                    <div class="form-group">
                        <%= f.text_area :text, rows: 10, placeholder: "Write your post here", value: @post.text %>
                    </div>
                    <div class="pt-1 mb-4">
                        <%= f.submit "Update", class: "btn btn-dark btn-lg btn-block" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/posts/index.html.erb
<div class="container-fluid mt-3">
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-header" style="background-color: #9A616D;">
                    <h3 class="card-title">Studiopost is an amazing community of artists, designers, and developers</h3>
                </div>
                <div class="card-body d-flex flex-column">
                    <p class="card-text text-center">Join us and share your work with the world</p>
                    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-block my-2", style: "background-color: #9A616D;" %>
                    <%= link_to "Log in", new_user_session_path, class: "btn btn-secondary btn-block my-2", style: "background-color: #9A616D;" %>
                </div>
            </div>

            <h3 class="mt-3">Popular posts</h3>

            <ul class="list-group">
                <% @popular_posts.each do |post| %>
                    <li class="list-group list-group-item">
                        <%= link_to post.title, user_post_path(post.user, post) %>
                    </li>
                <% end %>
            </ul>
        </div>
        <div class="col-md-9 overflow-auto">
            <div class="card">
                <div class="card-header" style="background-color: #9A616D;">
                    <h3 class="card-title text-center">Latest Posts</h3>
                </div>
                <div class="card-body">
                    <% @latest_posts.each do |post| %>
                        <div class="card mb-3">
                            <div class="card-header">
                                <h3 class="card-title <%= post.title.length > 50 ? "fs-5" : "fs-4" %>">
                                    <%= link_to post.title, user_post_path(post.user, post), style: "color: #9A616D;" %>
                                </h3>
                            </div>
                            <div class="card-body">
                                <p class="card-text">
                                    <%= markdown(post.text.truncate(200)) %>
                                </p>
                                <p class="card-text text-muted">
                                    Posted by <%= link_to post.user.username, user_path(post.user.username) %> on <%= post.created_at.strftime("%B %d, %Y") %>
                                </p>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<section style="background-color: #9A616D;" , class="vh-100">
  <div class="container py-5">
    <div class="row w-75 mx-auto" style="background-color: #FFF;>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title text-center py-3">Add a new post</h3>
            </div>      
            <div class="panel-body">
                <%= bootstrap_form_with model: @post, url:user_posts_path, method: :post do |f| %>
                    <div class="form-group">
                        <%= f.text_field :title, placeholder: "Post title here" %>
                    </div>
                    <div class="form-group">
                        <%= f.text_area :text, rows: 10, placeholder: "Write your post here" %>
                    </div>
                    <div class="pt-1 mb-4">
                        <%= f.submit "Create", class: "btn btn-dark btn-lg btn-block" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/posts/show.html.erb
<section style="background-color: #9A616D;">
    <div class="container py-5">
        <div class="card w-75 mx-auto" style="background-color: #FFF;">
            <div class="text-center py-3">
                <h3 class="card-title"> <%= @post.title %> </h3>
            </div>
            <div class="card-header d-flex justify-content-between">
                <p class="card-text">
                    <%= link_to '@' + @post.user.username, user_path(@post.user.username) %>
                    published <%= time_ago_in_words(@post.created_at) %>
                </p>
                <% if current_user == @post.user %>
                    <div class="card-text">
                        <%= link_to "Edit", edit_user_post_path(@post.user, @post), class: "btn btn-dark btn-sm" %>
                    </div>
                <% end %>
            </div>
            <div class="card-body">
                <%= markdown(@post.text) %>
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-between">
                    <%= form_with url: user_post_likes_path(@post.user, @post), method: :post do |f| %>
                        <%= f.submit " #{pluralize(@post.likes_counter, 'like')} ", class: "btn btn-outline-primary" %>
                    <% end %>
                    <button class="btn btn-link"><i class="fa fa-comment"></i> <%= @post.comments_counter %> Comments</button>
                </div>
                
                <h5 class="card-title my-2">Comments</h5>

                <ul class="list-group">
                    <% @post.comments.each do |comment| %>
                        <li class="list-group-item">
                            <div class="d-flex justify-content-between">
                                <div>
                                    <h6 class="card-title my-2">
                                        <%= comment.user.full_name %> 
                                        <% if comment.user == @post.user %>
                                            <span class="badge badge-primary">Author</span>
                                        <% end %>
                                    </h6>
                                    <p class="card-text"><%= comment.text %></p>
                                </div>
                                <div class="d-flex flex-column align-items-end">
                                    <p class="card-text"><i><%= time_ago_in_words(comment.created_at) %> ago</i></p>
                                    <% if current_user == comment.user %>       
                                        <%= form_with url: user_post_comment_path(@post.user, @post, comment), method: :delete do |form| %>
                                            <%= form.submit 'Delete comment', class: 'btn btn-danger btn-sm' %>
                                        <% end %>
                                    <% end %>
                                </div>
                            </div>
                        </li>
                    <% end %>
                </ul>

                <%= bootstrap_form_with model: @comment, url: user_post_comments_path(@post.user, @post), method: :post do |f| %>
                    <div class="form-group py-3">
                        <%= f.text_area :text, rows: 5, placeholder: "Write your comment here", hide_label: true %>
                    </div>
                    <div class="pt-1 mb-4">
                        <%= f.submit "Add Comment", class: "btn btn-dark btn-lg btn-block" %>
                    </div>
                <% end %>
                <hr />
                <div class="d-flex justify-content-between">
                    <p><%= link_to "Back to posts", user_posts_path(@post.user), class: "btn btn-primary btn-sm" %></p>
                    <% if current_user == @post.user %>
                        <%= form_with url: user_post_path(@post.user, @post), method: :delete do |f| %>
                            <%= f.submit 'Delete post', class: 'btn btn-danger btn-sm' %>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</section>
    
            